# -*- coding: utf-8 -*-
"""XSS_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPK-PSsG8cqXffpT-5_TpTutX4yyAlT0
"""

# Importing libraries
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# Mounting google colab
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

# Loading dataset
# Please change the path of dataset according to your directory
PATH_TO_DATASET = '/content/gdrive/MyDrive/XSS_dataset.csv'
dataset = pd.read_csv(PATH_TO_DATASET)

# dataset.shape
X = dataset['Sentence'].values
Y = dataset['Label'].values
# print(X)

# converting the text tnto vectors using TFIDF vectorizer
vectorizer = TfidfVectorizer(stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(X.astype('U')).toarray()

# splitting data into training and testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30)

# Training the Logistic Regression classifier for XSS 
model = LogisticRegression().fit(X_train, Y_train)

# Testing the classifier
Y_pred = model.predict(X_test)

# Calculating the accuracy on unseen testing data
print('Test accuracy of Logistic Regression classifier on XSS dataset is',accuracy_score(Y_test, Y_pred)*100)

# Saving the model
import pickle
import os
# Provide the location where you want to save the model in your machine
save_location = '/content/gdrive/MyDrive'
model_name = 'xss_model.sav'
save_model = {
    'model': model,
    'vectorizer' : vectorizer
}
pickle.dump(save_model, open(os.path.join(save_location, model_name), 'wb'))